@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Setup  [self-unpacking]
rem  Generated by Venv Batch Template Generator (Leon Priest / 7h3v01d) v3.4.0
rem  Generated on: 2026-07-03 18:36
rem
rem  Ship ONLY this file in your repo.  On first run it:
rem    1. Checks Python
rem    2. Creates / verifies the virtual environment
rem    3. Installs dependencies
rem    4. Writes companion scripts beside this file:
rem       run.bat  pip.bat  shell.bat  sync.bat  doctor.bat
rem
rem  Companion scripts are NOT overwritten if they already exist.
rem  Add them to .gitignore to keep your repo tidy.
rem ============================================================

set "PROJECT_NAME=Mardown Editor Pro"
set "VENV_DIR=.venv"

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setup: %PROJECT_NAME%
echo ============================================================
echo.

rem ── 1. Environment check + venv bootstrap ───────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Skipping creation.
    echo.
) else (
    echo [1/3] Creating virtual environment...
    echo ============================================================
    python -m venv "%VENV_DIR%"
    if errorlevel 1 ( echo [ERROR] venv creation failed. & pause & exit /b 1 )
    echo.

    echo [2/3] Upgrading pip...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo.

    if exist "requirements.txt" (
        echo [3/3] Installing dependencies from requirements.txt...
        echo ============================================================
        "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
        echo.
    ) else (
        echo [3/3] SKIPPED: No requirements.txt found.
        echo        Run sync.bat after adding dependencies.
        echo.
    )
)

rem ── 2. Write companion scripts ───────────────────────────────
echo ============================================================
echo  Writing companion scripts...
echo ============================================================
echo.

rem ── run.bat ─────────────────────────────────────────────────
set "OUTFILE=run.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_run_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbCBFbmFibGVEZWxheWVkRXhwYW5zaW9uDQpjZCAvZCAiJX5kcDAi
        echo DQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCBSdW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYg
        echo QmF0Y2ggVGVtcGxhdGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0K
        echo cmVtICBHZW5lcmF0ZWQgb246IDIwMjYtMDctMDMgMTg6MzYNCnJlbQ0KcmVtICBFTlRSWV9NT0RF
        echo Og0KcmVtICAgIGZpbGUgICAtPiBweXRob24gYXBwLnB5DQpyZW0gICAgbW9kdWxlIC0+IHB5dGhv
        echo biAtbSBwYWNrYWdlLm1vZHVsZQ0KcmVtICAgIHJ1bm5lciAtPiBweXRob24gLW0gcnVubmVyX21v
        echo ZHVsZSBbYXJncy4uLl0NCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNUX05BTUU9TWFyZG93biBFZGl0
        echo b3IgUHJvIg0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiRU5UUllfTU9ERT1maWxlIg0Kc2V0
        echo ICJBUFBfRU5UUlk9TWFya2Rvd25fRWRpdG9yX1Byby5weSINCnNldCAiUlVOTkVSX0FSR1M9Ig0K
        echo DQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUiDQoNCmlmIG5vdCBl
        echo eGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2NhbCB2ZW52IG5vdCBmb3VuZDogIiVQ
        echo WSUiDQogICAgZWNoby4NCiAgICBlY2hvIEZpeCB3aXRoOg0KICAgIGVjaG8gICBweXRob24gLW0g
        echo dmVudiAiJVZFTlZfRElSJSINCiAgICBlY2hvICAgIiVWRU5WX0RJUiVcU2NyaXB0c1xweXRob24u
        echo ZXhlIiAtbSBwaXAgaW5zdGFsbCAtLXVwZ3JhZGUgcGlwDQogICAgZWNobyAgICIlVkVOVl9ESVIl
        echo XFNjcmlwdHNccHl0aG9uLmV4ZSIgLW0gcGlwIGluc3RhbGwgLXIgcmVxdWlyZW1lbnRzLnR4dA0K
        echo ICAgIGVjaG8uDQogICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0KaWYgL0kgIiVFTlRSWV9N
        echo T0RFJSI9PSJmaWxlIiBpZiBub3QgZXhpc3QgIiVBUFBfRU5UUlklIiAoDQogICAgZWNobyBbRVJS
        echo T1JdIEVudHJ5IGZpbGUgbm90IGZvdW5kOiAiJUFQUF9FTlRSWSUiDQogICAgZWNobyBFZGl0IHJ1
        echo bi5iYXQgb3IgcnVuIHdpdGggdGhlIGNvcnJlY3QgZW50cnkgZmlsZS4NCiAgICBwYXVzZQ0KICAg
        echo IGV4aXQgL2IgMQ0KKQ0KDQp0aXRsZSAiJVBST0pFQ1RfTkFNRSUgLSBSVU4iDQplY2hvID09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0K
        echo ZWNobyAgUnVubmluZyA6ICVQUk9KRUNUX05BTUUlDQplY2hvICBQcm9qZWN0IDogJUNEJQ0KZWNo
        echo byAgUHl0aG9uICA6ICVQWSUNCmVjaG8gIE1vZGUgICAgOiAlRU5UUllfTU9ERSUNCmVjaG8gIEVu
        echo dHJ5ICAgOiAlQVBQX0VOVFJZJQ0KaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJydW5uZXIiIGVjaG8g
        echo IEFyZ3MgICAgOiAlUlVOTkVSX0FSR1MlDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNoby4NCg0Kc2V0ICJFWElUQ09E
        echo RT0wIg0KDQppZiAvSSAiJUVOVFJZX01PREUlIj09Im1vZHVsZSIgKA0KICAgICIlUFklIiAtbSAl
        echo QVBQX0VOVFJZJSAlKg0KKSBlbHNlIGlmIC9JICIlRU5UUllfTU9ERSUiPT0icnVubmVyIiAoDQog
        echo ICAgaWYgZGVmaW5lZCBSVU5ORVJfQVJHUyAoDQogICAgICAgICIlUFklIiAtbSAlQVBQX0VOVFJZ
        echo JSAhUlVOTkVSX0FSR1MhICUqDQogICAgKSBlbHNlICgNCiAgICAgICAgIiVQWSUiIC1tICVBUFBf
        echo RU5UUlklICUqDQogICAgKQ0KKSBlbHNlICgNCiAgICAiJVBZJSIgIiVBUFBfRU5UUlklIiAlKg0K
        echo KQ0KDQpzZXQgIkVYSVRDT0RFPSFFUlJPUkxFVkVMISINCg0KZWNoby4NCmVjaG8gPT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hv
        echo ICBQcm9jZXNzIGV4aXRlZCB3aXRoIGNvZGU6ICFFWElUQ09ERSENCmVjaG8gPT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0K
        echo ZXhpdCAvYiAhRVhJVENPREUhDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── pip.bat ─────────────────────────────────────────────────
set "OUTFILE=pip.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_pip_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QtbG9jYWwgcGlwIHdyYXBwZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxh
        echo dGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0
        echo ZWQgb246IDIwMjYtMDctMDMgMTg6MzYNCnJlbQ0KcmVtICBVc2FnZToNCnJlbSAgICBwaXAuYmF0
        echo IGluc3RhbGwgcmVxdWVzdHMNCnJlbSAgICBwaXAuYmF0IGluc3RhbGwgLXIgcmVxdWlyZW1lbnRz
        echo LnR4dA0KcmVtICAgIHBpcC5iYXQgZnJlZXplID4gcmVxdWlyZW1lbnRzLnR4dA0KcmVtICAgIHBp
        echo cC5iYXQgbGlzdA0KcmVtICAgIHBpcC5iYXQgdW5pbnN0YWxsIHJlcXVlc3RzDQpyZW0gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQoN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5
        echo dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2Nh
        echo bCB2ZW52IHdhcyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0K
        echo DQoiJVBZJSIgLW0gcGlwICUqDQpleGl0IC9iICVFUlJPUkxFVkVMJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── shell.bat ─────────────────────────────────────────────────
set "OUTFILE=shell.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_shell_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpjZCAvZCAiJX5kcDAiDQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCB2ZW52IHNo
        echo ZWxsDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRvciAoTGVv
        echo biBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2LTA3LTAz
        echo IDE4OjM2DQpyZW0NCnJlbSAgT3BlbnMgYW4gYWN0aXZhdGVkIENNRCBzZXNzaW9uIGZvciB0aGlz
        echo IHByb2plY3QuDQpyZW0gIFVzZSBvbmx5IHdoZW4geW91IG5lZWQgYW4gaW50ZXJhY3RpdmUgdmVu
        echo diBzZXNzaW9uLg0KcmVtICBFeGl0IHdpdGg6IGV4aXQNCnJlbSA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNU
        echo X05BTUU9TWFyZG93biBFZGl0b3IgUHJvIg0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiQUNU
        echo SVZBVEU9JUNEJVwlVkVOVl9ESVIlXFNjcmlwdHNcYWN0aXZhdGUuYmF0Ig0KDQppZiBub3QgZXhp
        echo c3QgIiVBQ1RJVkFURSUiICgNCiAgICBlY2hvIFtFUlJPUl0gTG9jYWwgdmVudiB3YXMgbm90IGZv
        echo dW5kOg0KICAgIGVjaG8gICAgICAgICAiJUFDVElWQVRFJSINCiAgICBlY2hvLg0KICAgIGVjaG8g
        echo Q3JlYXRlIGl0IHdpdGg6DQogICAgZWNobyAgICAgICAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9E
        echo SVIlIg0KICAgIGVjaG8uDQogICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0KdGl0bGUgIiVQ
        echo Uk9KRUNUX05BTUUlIC0gVkVOViBTSEVMTCINCmNhbGwgIiVBQ1RJVkFURSUiDQoNCmVjaG8gPT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo DQplY2hvICBQcm9qZWN0IHNoZWxsIGFjdGl2YXRlZA0KZWNobyAgUHJvamVjdDogIiVDRCUiDQpl
        echo Y2hvICBQeXRob24gOg0Kd2hlcmUgcHl0aG9uDQplY2hvICBUeXBlICJleGl0IiB0byBsZWF2ZSB0
        echo aGlzIHNoZWxsLg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT0NCmVjaG8uDQpjbWQgL2sNCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── sync.bat ─────────────────────────────────────────────────
set "OUTFILE=sync.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_sync_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIERlcGVu
        echo ZGVuY3kgU3luYyAocGlwKQ0KcmVtICBHZW5lcmF0ZWQgYnkgVmVudiBCYXRjaCBUZW1wbGF0ZSBH
        echo ZW5lcmF0b3IgKExlb24gUHJpZXN0IC8gN2gzdjAxZCkgdjMuNC4wDQpyZW0gIEdlbmVyYXRlZCBv
        echo bjogMjAyNi0wNy0wMyAxODozNg0KcmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1NYXJkb3du
        echo IEVkaXRvciBQcm8iDQpzZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJQWT0lQ0QlXCVWRU5WX0RJ
        echo UiVcU2NyaXB0c1xweXRob24uZXhlIg0KDQppZiBub3QgZXhpc3QgIiVQWSUiICgNCiAgICBlY2hv
        echo IFtFUlJPUl0gTG9jYWwgdmVudiBub3QgZm91bmQ6ICIlUFklIg0KICAgIGVjaG8uDQogICAgZWNo
        echo byBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgcHl0aG9uIC1tIHZlbnYgIiVWRU5WX0RJUiUi
        echo DQogICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0KdGl0bGUgIiVQUk9KRUNUX05BTUUlIC0g
        echo U1lOQyINCg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT0NCmVjaG8gIFN5bmNpbmc6ICVQUk9KRUNUX05BTUUlDQplY2hvICBQ
        echo eXRob24gOiAlUFklDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PQ0KZWNoby4NCg0KZWNobyBbMS8zXSBVcGdyYWRpbmcgcGlw
        echo Li4uDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PQ0KIiVQWSUiIC1tIHBpcCBpbnN0YWxsIC0tdXBncmFkZSBwaXANCmVjaG8u
        echo DQoNCmlmIGV4aXN0ICJyZXF1aXJlbWVudHMudHh0IiAoDQogICAgZWNobyBbMi8zXSBJbnN0YWxs
        echo aW5nIGZyb20gcmVxdWlyZW1lbnRzLnR4dC4uLg0KICAgIGVjaG8gPT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQogICAgIiVQWSUiIC1t
        echo IHBpcCBpbnN0YWxsIC1yIHJlcXVpcmVtZW50cy50eHQNCiAgICBlY2hvLg0KKSBlbHNlICgNCiAg
        echo ICBlY2hvIFsyLzNdIFNLSVBQRUQ6IE5vIHJlcXVpcmVtZW50cy50eHQgZm91bmQuDQogICAgZWNo
        echo byAgICAgICBDcmVhdGUgb25lIHdpdGg6IHBpcC5iYXQgZnJlZXplIF4+IHJlcXVpcmVtZW50cy50
        echo eHQNCiAgICBlY2hvLg0KKQ0KDQplY2hvIFszLzNdIERlcGVuZGVuY3kgaGVhbHRoIGNoZWNrLi4u
        echo DQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PQ0KIiVQWSUiIC1tIHBpcCBjaGVjaw0KZWNoby4NCg0KZWNobyA9PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8g
        echo IFNZTkMgQ09NUExFVEUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhpdCAvYiAwDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── doctor.bat ─────────────────────────────────────────────────
set "OUTFILE=doctor.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_doctor_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgRG9jdG9yDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRv
        echo ciAoTGVvbiBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2
        echo LTA3LTAzIDE4OjM2DQpyZW0gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQoNCnNldCAiUFJPSkVDVF9OQU1FPU1hcmRvd24gRWRpdG9y
        echo IFBybyINCnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIkVOVFJZX01PREU9ZmlsZSINCnNldCAi
        echo QVBQX0VOVFJZPU1hcmtkb3duX0VkaXRvcl9Qcm8ucHkiDQpzZXQgIlJVTk5FUl9BUkdTPSINCnNl
        echo dCAiUFk9JUNEJVwlVkVOVl9ESVIlXFNjcmlwdHNccHl0aG9uLmV4ZSINCg0KZWNobyA9PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVj
        echo aG8gIFBST0pFQ1QgRE9DVE9SOiAlUFJPSkVDVF9OQU1FJQ0KZWNobyA9PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFByb2pl
        echo Y3QgOiAlQ0QlDQplY2hvICBNb2RlICAgIDogJUVOVFJZX01PREUlDQplY2hvICBFbnRyeSAgIDog
        echo JUFQUF9FTlRSWSUNCmlmIC9JICIlRU5UUllfTU9ERSUiPT0icnVubmVyIiBlY2hvICBBcmdzICAg
        echo IDogJVJVTk5FUl9BUkdTJQ0KZWNoby4NCg0KaWYgbm90IGV4aXN0ICIlUFklIiAoDQogICAgZWNo
        echo byBbRkFJTF0gdmVudiBub3QgZm91bmQgYXQ6ICIlUFklIg0KICAgIGVjaG8uDQogICAgZWNobyBD
        echo cmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgcHl0aG9uIC1tIHZlbnYgIiVWRU5WX0RJUiUiDQog
        echo ICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0KZWNobyBbT0tdIHZlbnYgZm91bmQ6ICIlUFkl
        echo Ig0KZWNoby4NCg0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVjaG8gIFB5dGhvbiBFbnZpcm9ubWVudA0KZWNobyAtLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0N
        echo CiIlUFklIiAtYyAiaW1wb3J0IHN5czsgcHJpbnQoJ0V4ZWN1dGFibGUgOicsIHN5cy5leGVjdXRh
        echo YmxlKTsgcHJpbnQoJ1ZlcnNpb24gICAgOicsIHN5cy52ZXJzaW9uLnNwbGl0KClbMF0pOyBwcmlu
        echo dCgnUHJlZml4ICAgICA6Jywgc3lzLnByZWZpeCkiDQplY2hvLg0KDQplY2hvIC0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KZWNobyAg
        echo cGlwIHZlcnNpb24NCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoiJVBZJSIgLW0gcGlwIC0tdmVyc2lvbg0KZWNoby4NCg0K
        echo ZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0NCmVjaG8gIEluc3RhbGxlZCBQYWNrYWdlcw0KZWNobyAtLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCiIlUFklIiAtbSBw
        echo aXAgbGlzdA0KZWNoby4NCg0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVjaG8gIERlcGVuZGVuY3kgSGVhbHRoDQplY2hv
        echo IC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLQ0KIiVQWSUiIC1tIHBpcCBjaGVjaw0KZWNoby4NCg0KZWNobyAtLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVjaG8gIEVudHJ5
        echo IFBvaW50IENoZWNrDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJmaWxlIiAoDQog
        echo ICAgaWYgZXhpc3QgIiVBUFBfRU5UUlklIiAoDQogICAgICAgIGVjaG8gW09LXSBFbnRyeSBmaWxl
        echo IGZvdW5kOiAiJUFQUF9FTlRSWSUiDQogICAgKSBlbHNlICgNCiAgICAgICAgZWNobyBbRkFJTF0g
        echo RW50cnkgZmlsZSBOT1QgZm91bmQ6ICIlQVBQX0VOVFJZJSINCiAgICApDQopIGVsc2UgKA0KICAg
        echo ICIlUFklIiAtYyAiaW1wb3J0IGltcG9ydGxpYi51dGlsLCBzeXM7IG5hbWU9ciclQVBQX0VOVFJZ
        echo JSc7IHNwZWM9aW1wb3J0bGliLnV0aWwuZmluZF9zcGVjKG5hbWUpOyBwcmludCgoJ1tPS10gTW9k
        echo dWxlIGZvdW5kOiAnIGlmIHNwZWMgZWxzZSAnW0ZBSUxdIE1vZHVsZSBOT1QgZm91bmQ6ICcpICsg
        echo bmFtZSk7IHN5cy5leGl0KDAgaWYgc3BlYyBlbHNlIDEpIiAyPm51bA0KICAgIGlmIGVycm9ybGV2
        echo ZWwgMSBlY2hvIFtGQUlMXSBNb2R1bGUgaW1wb3J0IHRlc3QgZmFpbGVkLg0KICAgIGlmIC9JICIl
        echo RU5UUllfTU9ERSUiPT0icnVubmVyIiBlY2hvIFtJTkZPXSBSdW5uZXIgYXJnczogIiVSVU5ORVJf
        echo QVJHUyUiDQopDQplY2hvLg0KDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KZWNobyAgUHJvamVjdCBGaWxlcw0KZWNobyAt
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0NCmlmIGV4aXN0ICJ1di5sb2NrIiAgICAgICAgICBlY2hvIFtPS10gICB1di5sb2NrIGZvdW5k
        echo DQppZiBleGlzdCAicHlwcm9qZWN0LnRvbWwiICAgZWNobyBbT0tdICAgcHlwcm9qZWN0LnRvbWwg
        echo Zm91bmQNCmlmIGV4aXN0ICJyZXF1aXJlbWVudHMudHh0IiBlY2hvIFtPS10gICByZXF1aXJlbWVu
        echo dHMudHh0IGZvdW5kDQppZiBub3QgZXhpc3QgInJlcXVpcmVtZW50cy50eHQiIGVjaG8gW1dBUk5d
        echo IHJlcXVpcmVtZW50cy50eHQgbWlzc2luZw0KZWNoby4NCg0KZWNobyA9PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIERPQ1RP
        echo UiBDT01QTEVURQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT0NCnBhdXNlDQpleGl0IC9iIDANCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo.
echo  Companion scripts written (existing files were NOT overwritten).
echo  Add them to .gitignore to keep your repo tidy.
echo.
echo  Next steps:
echo    run.bat    - Launch %PROJECT_NAME%
echo    sync.bat   - Reinstall / update dependencies
echo    shell.bat  - Open activated venv shell
echo    doctor.bat - Environment health check
echo    pip.bat    - Project-local pip wrapper
rem (test.bat not included)
echo ============================================================
pause
exit /b 0
